package com.example.ui.theme

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF0041a2)
val md_theme_light_onPrimary = Color(0xFFffffff)
val md_theme_light_primaryContainer = Color(0xFF0b57d0)
val md_theme_light_onPrimaryContainer = Color(0xFFced9ff)
val md_theme_light_secondary = Color(0xFF016d32)
val md_theme_light_onSecondary = Color(0xFFffffff)
val md_theme_light_secondaryContainer = Color(0xFF9bf7ac)
val md_theme_light_onSecondaryContainer = Color(0xFF0f7438)
val md_theme_light_tertiary = Color(0xFF314579)
val md_theme_light_onTertiary = Color(0xFFffffff)
val md_theme_light_tertiaryContainer = Color(0xFF495d92)
val md_theme_light_onTertiaryContainer = Color(0xFFcdd8ff)
val md_theme_light_error = Color(0xFFba1a1a)
val md_theme_light_errorContainer = Color(0xFFffdad6)
val md_theme_light_onError = Color(0xFFffffff)
val md_theme_light_onErrorContainer = Color(0xFF93000a)
val md_theme_light_background = Color(0xFFfbf8fe)
val md_theme_light_onBackground = Color(0xFF1b1b1f)
val md_theme_light_surface = Color(0xFFfbf8fe)
val md_theme_light_onSurface = Color(0xFF1b1b1f)
val md_theme_light_surfaceVariant = Color(0xFFe4e1e7)
val md_theme_light_onSurfaceVariant = Color(0xFF424654)
val md_theme_light_outline = Color(0xFF737785)
val md_theme_light_inverseOnSurface = Color(0xFFf3f0f5)
val md_theme_light_inverseSurface = Color(0xFF303034)
val md_theme_light_inversePrimary = Color(0xFFb2c5ff)
val md_theme_light_surfaceTint = Color(0xFF0856cf)
val md_theme_light_outlineVariant = Color(0xFFc3c6d6)
val md_theme_light_scrim = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFFdae2ff)
val md_theme_dark_onPrimary = Color(0xFF001847)
val md_theme_dark_primaryContainer = Color(0xFF0040a1)
val md_theme_dark_onPrimaryContainer = Color(0xFFb2c5ff)
val md_theme_dark_secondary = Color(0xFF9bf7ac)
val md_theme_dark_onSecondary = Color(0xFF00210b)
val md_theme_dark_secondaryContainer = Color(0xFF005224)
val md_theme_dark_onSecondaryContainer = Color(0xFF7fda92)
val md_theme_dark_tertiary = Color(0xFFdae2ff)
val md_theme_dark_onTertiary = Color(0xFF001848)
val md_theme_dark_tertiaryContainer = Color(0xFF304578)
val md_theme_dark_onTertiaryContainer = Color(0xFFb2c5ff)
val md_theme_dark_error = Color(0xFFffb4ab)
val md_theme_dark_errorContainer = Color(0xFF93000a)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFffdad6)
val md_theme_dark_background = Color(0xFF1b1b1f)
val md_theme_dark_onBackground = Color(0xFFe4e1e7)
val md_theme_dark_surface = Color(0xFF1b1b1f)
val md_theme_dark_onSurface = Color(0xFFe4e1e7)
val md_theme_dark_surfaceVariant = Color(0xFF424654)
val md_theme_dark_onSurfaceVariant = Color(0xFFc3c6d6)
val md_theme_dark_outline = Color(0xFF8d919f)
val md_theme_dark_inverseOnSurface = Color(0xFF1b1b1f)
val md_theme_dark_inverseSurface = Color(0xFFe4e1e7)
val md_theme_dark_inversePrimary = Color(0xFF0041a2)
val md_theme_dark_surfaceTint = Color(0xFFb2c5ff)
val md_theme_dark_outlineVariant = Color(0xFF424654)
val md_theme_dark_scrim = Color(0xFF000000)

val SurfaceContainerLowestLight = Color(0xFFffffff)
val SurfaceContainerLowLight = Color(0xFFf6f2f8)
val SurfaceContainerLight = Color(0xFFf0edf2)
val SurfaceContainerHighLight = Color(0xFFeae7ed)
val SurfaceContainerHighestLight = Color(0xFFe4e1e7)

val SurfaceContainerLowestDark = Color(0xFF0f0f13)
val SurfaceContainerLowDark = Color(0xFF1a1a1e)
val SurfaceContainerDark = Color(0xFF202024)
val SurfaceContainerHighDark = Color(0xFF2a2a2e)
val SurfaceContainerHighestDark = Color(0xFF353539)
